import pandas as pd
df=pd.read_csv("online_store_customer_order.csv")
print(df.head())
print(df.info())
print(df.describe())
print("Mean amount spent by customers: ", df["Amount_spent"].mean())
print("max: ", df["Amount_spent"].max())
print("min: ", df["Amount_spent"].min())
print(df["Gender"].value_counts())
print(df["Payment_method"].value_counts())
print(df["State_names"].value_counts())
print(df.isnull().sum())
groped = df.groupby("State_names")["Amount_spent"].mean()
print(groped)
statee_by_category = df.groupby("State_names")["Age"].agg(["min", "max", "count"])
print(statee_by_category)
